version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing Python dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build complete (nothing to compile for Flask)

artifacts:
  files:
    - '**/*'
